# Generated by Django 4.0.6 on 2024-07-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0007_director_fotografia_genero_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='director',
            name='fotografia',
        ),
        migrations.AddField(
            model_name='director',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='directores/'),
        ),
    ]
