# Generated by Django 4.0.6 on 2024-07-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0009_cine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cine',
            name='direccion',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='cine',
            name='telefono',
            field=models.CharField(default='', max_length=150),
        ),
    ]
