# Generated by Django 4.0.6 on 2024-08-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0010_alter_cine_direccion_alter_cine_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='duracion',
            field=models.TimeField(null=True),
        ),
    ]
